export const WORK_TYPES = [
  { value: "freelance_service", label: "Freelance service job" },
  { value: "part_time_day_wage", label: "Part-time day-wage job" },
  { value: "long_duration_shift", label: "Long-duration shift work" },
] as const;

export const SHIFT_NICHES = [
  {
    value: "healthcare",
    label: "Healthcare",
    industry: "Healthcare",
    roles: ["Healthcare support worker", "Care assistant", "Clinic support", "Hospital porter"],
    hourlyAverage: 22,
    dayAverage: 165,
  },
  {
    value: "hospitality",
    label: "Hospitality",
    industry: "Hospitality",
    roles: ["Wait staff", "Bar staff", "Kitchen porter", "Host"],
    hourlyAverage: 17,
    dayAverage: 130,
  },
  {
    value: "cleaning",
    label: "Cleaning",
    industry: "Cleaning",
    roles: ["Commercial cleaner", "Housekeeping", "Deep-clean crew", "Site cleaner"],
    hourlyAverage: 18,
    dayAverage: 135,
  },
  {
    value: "retail",
    label: "Retail",
    industry: "Retail",
    roles: ["Retail assistant", "Stock assistant", "Cashier", "Customer support"],
    hourlyAverage: 16,
    dayAverage: 120,
  },
  {
    value: "logistics",
    label: "Logistics",
    industry: "Logistics",
    roles: ["Warehouse operative", "Picker packer", "Loading assistant", "Driver helper"],
    hourlyAverage: 18,
    dayAverage: 140,
  },
  {
    value: "events",
    label: "Events",
    industry: "Events",
    roles: ["Event staff", "Brand ambassador", "Ticketing support", "Setup crew"],
    hourlyAverage: 18,
    dayAverage: 140,
  },
  {
    value: "home_help",
    label: "Home help",
    industry: "Home help",
    roles: ["Home assistant", "Meal prep assistant", "Errand runner", "Companion support"],
    hourlyAverage: 18,
    dayAverage: 135,
  },
  {
    value: "childcare",
    label: "Childcare",
    industry: "Childcare",
    roles: ["Babysitter", "After-school helper", "Holiday care assistant", "Child activity support"],
    hourlyAverage: 17,
    dayAverage: 130,
  },
  {
    value: "pet_care",
    label: "Pet care",
    industry: "Pet care",
    roles: ["Dog walker", "Pet sitter", "Home pet visitor", "Pet transport helper"],
    hourlyAverage: 16,
    dayAverage: 120,
  },
  {
    value: "it_support",
    label: "IT support",
    industry: "IT support",
    roles: ["IT support technician", "Device setup helper", "Network setup assistant", "Software support"],
    hourlyAverage: 24,
    dayAverage: 185,
  },
  {
    value: "education",
    label: "Education and tutoring",
    industry: "Education and tutoring",
    roles: ["Private tutor", "Homework helper", "Language tutor", "Music lesson assistant"],
    hourlyAverage: 24,
    dayAverage: 180,
  },
  {
    value: "handyman",
    label: "Handyman and maintenance",
    industry: "Handyman and maintenance",
    roles: ["Maintenance worker", "Furniture assembler", "Repair assistant", "Painting helper"],
    hourlyAverage: 22,
    dayAverage: 170,
  },
  {
    value: "gardening",
    label: "Gardening",
    industry: "Gardening",
    roles: ["Gardener", "Lawn care worker", "Hedge trimming helper", "Garden cleanup crew"],
    hourlyAverage: 19,
    dayAverage: 145,
  },
  {
    value: "moving",
    label: "Moving",
    industry: "Moving",
    roles: ["Moving helper", "Packing assistant", "Furniture mover", "Heavy lifting assistant"],
    hourlyAverage: 20,
    dayAverage: 155,
  },
  {
    value: "security",
    label: "Security",
    industry: "Security",
    roles: ["Security guard", "Door supervisor", "Event security", "Site watch"],
    hourlyAverage: 20,
    dayAverage: 155,
  },
  {
    value: "beauty_wellness",
    label: "Beauty and wellness",
    industry: "Beauty and wellness",
    roles: ["Salon assistant", "Spa attendant", "Makeup assistant", "Wellness reception"],
    hourlyAverage: 18,
    dayAverage: 135,
  },
  {
    value: "automotive",
    label: "Automotive",
    industry: "Automotive",
    roles: ["Vehicle cleaner", "Garage assistant", "Driver helper", "Car delivery support"],
    hourlyAverage: 19,
    dayAverage: 145,
  },
  {
    value: "winter_services",
    label: "Winter services",
    industry: "Winter services",
    roles: ["Snow removal worker", "Winter pet sitter", "Holiday cover helper", "Seasonal support worker"],
    hourlyAverage: 20,
    dayAverage: 150,
  },
] as const;

export type WorkType = (typeof WORK_TYPES)[number]["value"];
export type ShiftNiche = (typeof SHIFT_NICHES)[number]["value"];

export function getShiftNiche(value?: string | null) {
  return SHIFT_NICHES.find((niche) => niche.value === value) || SHIFT_NICHES[0];
}
