export type TaskrabbitService = {
  title: string;
  slug: string;
  taskrabbitPath: string;
};

export type TaskrabbitCategory = {
  title: string;
  slug: string;
  taskrabbitPath: string;
  services: TaskrabbitService[];
};

export const TASKRABBIT_CATEGORIES: TaskrabbitCategory[] = [
  {
    title: "Featured Tasks",
    slug: "featured",
    taskrabbitPath: "/services/featured",
    services: [
      { title: "Furniture Assembly", slug: "assemble-furniture", taskrabbitPath: "/services/featured/assemble-furniture" },
      { title: "Home Repairs", slug: "general-handyman", taskrabbitPath: "/services/featured/general-handyman" },
      { title: "Help Moving", slug: "help-moving", taskrabbitPath: "/services/featured/help-moving" },
      { title: "Yard Work Services", slug: "yard-work-removal", taskrabbitPath: "/services/featured/yard-work-removal" },
      { title: "Spring Cleaning", slug: "spring-cleaning", taskrabbitPath: "/services/featured/spring-cleaning" },
      { title: "TV Mounting", slug: "wall-mount-tv", taskrabbitPath: "/services/featured/wall-mount-tv" },
      { title: "Plumbing", slug: "plumbing", taskrabbitPath: "/services/featured/plumbing" },
      { title: "Hang Art, Mirror & Decor", slug: "hang-pictures", taskrabbitPath: "/services/featured/hang-pictures" },
      { title: "Electrical Help", slug: "electrical-work", taskrabbitPath: "/services/featured/electrical-work" },
      { title: "Wait in Line", slug: "waiting-in-line", taskrabbitPath: "/services/featured/waiting-in-line" },
      { title: "Closet Organization Service", slug: "closet-organization", taskrabbitPath: "/services/featured/closet-organization" },
    ],
  },
  {
    title: "Handyman",
    slug: "handyman",
    taskrabbitPath: "/services/handyman",
    services: [
      { title: "Door, Cabinet, & Furniture Repair", slug: "door-and-cabinet-repair", taskrabbitPath: "/services/handyman/door-and-cabinet-repair" },
      { title: "Appliance Installation & Repairs", slug: "appliance-repairs", taskrabbitPath: "/services/handyman/appliance-repairs" },
      { title: "Furniture Assembly", slug: "assemble-furniture", taskrabbitPath: "/services/handyman/assemble-furniture" },
      { title: "TV Mounting", slug: "wall-mount-tv", taskrabbitPath: "/services/handyman/wall-mount-tv" },
      { title: "Drywall Repair Service", slug: "drywall-repair", taskrabbitPath: "/services/handyman/drywall-repair" },
      { title: "Flooring & Tiling Help", slug: "flooring-tiling-help", taskrabbitPath: "/services/handyman/flooring-tiling-help" },
      { title: "Electrical Help", slug: "electrical-work", taskrabbitPath: "/services/handyman/electrical-work" },
      { title: "Sealing & Caulking", slug: "sealing-caulking", taskrabbitPath: "/services/handyman/sealing-caulking" },
      { title: "Plumbing", slug: "plumbing", taskrabbitPath: "/services/handyman/plumbing" },
      { title: "Window & Blinds Repair", slug: "window-repair", taskrabbitPath: "/services/handyman/window-repair" },
      { title: "Ceiling Fan Installation", slug: "ceiling-fan-installation", taskrabbitPath: "/services/handyman/ceiling-fan-installation" },
      { title: "Smart Home Installation", slug: "smart-home-installation", taskrabbitPath: "/services/handyman/smart-home-installation" },
      { title: "Heavy Lifting", slug: "heavy-lifting", taskrabbitPath: "/services/handyman/heavy-lifting" },
      { title: "Install Air Conditioner", slug: "install-air-conditioner", taskrabbitPath: "/services/handyman/install-air-conditioner" },
      { title: "Painting", slug: "painting", taskrabbitPath: "/services/handyman/painting" },
      { title: "Install Shelves, Rods & Hooks", slug: "shelf-mounting", taskrabbitPath: "/services/handyman/shelf-mounting" },
      { title: "Home Maintenance", slug: "home-maintenance", taskrabbitPath: "/services/handyman/home-maintenance" },
      { title: "Install Blinds & Window Treatments", slug: "blinds-installation", taskrabbitPath: "/services/handyman/blinds-installation" },
      { title: "Home Repairs", slug: "general-handyman", taskrabbitPath: "/services/handyman/general-handyman" },
      { title: "Baby Proofing", slug: "baby-proofing", taskrabbitPath: "/services/handyman/baby-proofing" },
      { title: "Yard Work Services", slug: "yard-work-removal", taskrabbitPath: "/services/handyman/yard-work-removal" },
      { title: "Light Installation", slug: "light-installation", taskrabbitPath: "/services/handyman/light-installation" },
      { title: "Carpentry Services", slug: "carpentry-construction", taskrabbitPath: "/services/handyman/carpentry-construction" },
      { title: "Hang Art, Mirror & Decor", slug: "hang-pictures", taskrabbitPath: "/services/handyman/hang-pictures" },
      { title: "General Mounting", slug: "mounting-all", taskrabbitPath: "/services/handyman/mounting-all" },
      { title: "Cabinet Installation", slug: "cabinet-installation", taskrabbitPath: "/services/handyman/cabinet-installation" },
      { title: "Wallpapering Service", slug: "wallpapering", taskrabbitPath: "/services/handyman/wallpapering" },
      { title: "Fence Installation & Repair Services", slug: "fence-installation", taskrabbitPath: "/services/handyman/fence-installation" },
      { title: "Deck Restoration Services", slug: "deck-restoration", taskrabbitPath: "/services/handyman/deck-restoration" },
      { title: "Doorbell Installation", slug: "doorbell-installation", taskrabbitPath: "/services/handyman/doorbell-installation" },
      { title: "Home Theater Installing", slug: "home-theater-setup", taskrabbitPath: "/services/handyman/home-theater-setup" },
    ],
  },
  {
    title: "Moving Services",
    slug: "moving",
    taskrabbitPath: "/services/moving",
    services: [
      { title: "Help Moving", slug: "help-moving", taskrabbitPath: "/services/moving/help-moving" },
      { title: "Truck Assisted Help Moving", slug: "truck-assisted-help-moving", taskrabbitPath: "/services/moving/truck-assisted-help-moving" },
      { title: "Packing Services & Help", slug: "packing", taskrabbitPath: "/services/moving/packing" },
      { title: "Unpacking Services", slug: "unpacking", taskrabbitPath: "/services/moving/unpacking" },
      { title: "Heavy Lifting", slug: "heavy-lifting", taskrabbitPath: "/services/moving/heavy-lifting" },
      { title: "Local Movers", slug: "local-movers", taskrabbitPath: "/services/moving/local-movers" },
      { title: "Junk Pickup", slug: "junk-removal", taskrabbitPath: "/services/moving/junk-removal" },
      { title: "Furniture Movers", slug: "furniture-movers", taskrabbitPath: "/services/moving/furniture-movers" },
      { title: "One Item Movers", slug: "one-piece-of-furniture", taskrabbitPath: "/services/moving/one-piece-of-furniture" },
      { title: "Storage Unit Moving", slug: "storage-unit-moving", taskrabbitPath: "/services/moving/storage-unit-moving" },
      { title: "Couch Removal", slug: "couch-removal", taskrabbitPath: "/services/moving/couch-removal" },
      { title: "Mattress Pick-Up & Removal", slug: "mattress-removal", taskrabbitPath: "/services/moving/mattress-removal" },
      { title: "Furniture Removal", slug: "furniture-removal", taskrabbitPath: "/services/moving/furniture-removal" },
      { title: "Pool Table Movers", slug: "pool-table-movers", taskrabbitPath: "/services/moving/pool-table-movers" },
      { title: "Appliance Removal", slug: "appliance-removal", taskrabbitPath: "/services/moving/appliance-removal" },
      { title: "Heavy Furniture Moving", slug: "heavy-furniture", taskrabbitPath: "/services/moving/heavy-furniture" },
      { title: "Rearranging Furniture", slug: "rearranging-furniture", taskrabbitPath: "/services/moving/rearranging-furniture" },
      { title: "Full Service Help Moving", slug: "full-service-movers", taskrabbitPath: "/services/moving/full-service-movers" },
      { title: "In-Home Furniture Movers", slug: "in-home-furniture-movers", taskrabbitPath: "/services/moving/in-home-furniture-movers" },
    ],
  },
  {
    title: "Furniture Assembly",
    slug: "furniture-assembly",
    taskrabbitPath: "/services/furniture-assembly",
    services: [
      { title: "Furniture Assembly", slug: "assemble-furniture", taskrabbitPath: "/services/furniture-assembly/assemble-furniture" },
      { title: "Patio Furniture Assembly", slug: "patio-furniture-assembly", taskrabbitPath: "/services/furniture-assembly/patio-furniture-assembly" },
      { title: "Desk Assembly", slug: "desk-assembly", taskrabbitPath: "/services/furniture-assembly/desk-assembly" },
      { title: "Dresser Assembly", slug: "dresser-assembly", taskrabbitPath: "/services/furniture-assembly/dresser-assembly" },
      { title: "Bed Assembly", slug: "bed-assembly", taskrabbitPath: "/services/furniture-assembly/bed-assembly" },
      { title: "Bookshelf Assembly", slug: "bookshelf-assembly", taskrabbitPath: "/services/furniture-assembly/bookshelf-assembly" },
      { title: "Couch Assembly", slug: "couch-assembly", taskrabbitPath: "/services/furniture-assembly/couch-assembly" },
      { title: "Chair Assembly", slug: "chair-assembly", taskrabbitPath: "/services/furniture-assembly/chair-assembly" },
      { title: "Wardrobe Assembly", slug: "wardrobe-assembly", taskrabbitPath: "/services/furniture-assembly/wardrobe-assembly" },
      { title: "Table Assembly", slug: "table-assembly", taskrabbitPath: "/services/furniture-assembly/table-assembly" },
      { title: "Disassemble furniture", slug: "furniture-disassembly", taskrabbitPath: "/services/furniture-assembly/furniture-disassembly" },
    ],
  },
  {
    title: "Mounting & Installation",
    slug: "mounting",
    taskrabbitPath: "/services/mounting",
    services: [
      { title: "TV Mounting", slug: "wall-mount-tv", taskrabbitPath: "/services/mounting/wall-mount-tv" },
      { title: "Install Shelves, Rods & Hooks", slug: "shelf-mounting", taskrabbitPath: "/services/mounting/shelf-mounting" },
      { title: "Ceiling Fan Installation", slug: "ceiling-fan-installation", taskrabbitPath: "/services/mounting/ceiling-fan-installation" },
      { title: "Install Blinds & Window Treatments", slug: "blinds-installation", taskrabbitPath: "/services/mounting/blinds-installation" },
      { title: "Hang Art, Mirror & Decor", slug: "hang-pictures", taskrabbitPath: "/services/mounting/hang-pictures" },
      { title: "General Mounting", slug: "mounting-all", taskrabbitPath: "/services/mounting/mounting-all" },
      { title: "Hang Christmas Lights", slug: "christmas-light-installation", taskrabbitPath: "/services/mounting/christmas-light-installation" },
    ],
  },
  {
    title: "Cleaning",
    slug: "cleaning",
    taskrabbitPath: "/services/cleaning",
    services: [
      { title: "House Cleaning Services", slug: "house-cleaning", taskrabbitPath: "/services/cleaning/house-cleaning" },
      { title: "Deep Cleaning", slug: "deep-cleaning", taskrabbitPath: "/services/cleaning/deep-cleaning" },
      { title: "Disinfecting Services", slug: "disinfecting-service", taskrabbitPath: "/services/cleaning/disinfecting-service" },
      { title: "Move In Cleaning", slug: "move-in", taskrabbitPath: "/services/cleaning/move-in" },
      { title: "Move Out Cleaning", slug: "move-out", taskrabbitPath: "/services/cleaning/move-out" },
      { title: "Vacation Rental Cleaning", slug: "airbnb", taskrabbitPath: "/services/cleaning/airbnb" },
      { title: "Carpet Cleaning Service", slug: "carpet-cleaning", taskrabbitPath: "/services/cleaning/carpet-cleaning" },
      { title: "Garage Cleaning", slug: "garage-cleaning", taskrabbitPath: "/services/cleaning/garage-cleaning" },
      { title: "One Time Cleaning Services", slug: "one-time", taskrabbitPath: "/services/cleaning/one-time" },
      { title: "Car Washing", slug: "mobile-car-wash", taskrabbitPath: "/services/cleaning/mobile-car-wash" },
      { title: "Laundry Help", slug: "laundry-help", taskrabbitPath: "/services/cleaning/laundry-help" },
      { title: "Pressure Washing", slug: "pressure-washing", taskrabbitPath: "/services/cleaning/pressure-washing" },
      { title: "Spring Cleaning", slug: "spring-cleaning", taskrabbitPath: "/services/cleaning/spring-cleaning" },
    ],
  },
  {
    title: "Shopping + Delivery",
    slug: "shopping-delivery",
    taskrabbitPath: "/services/shopping-delivery",
    services: [
      { title: "Delivery Service", slug: "delivery-service", taskrabbitPath: "/services/shopping-delivery/delivery-service" },
      { title: "Grocery Shopping & Delivery", slug: "grocery-shopping", taskrabbitPath: "/services/shopping-delivery/grocery-shopping" },
      { title: "Running Your Errands", slug: "run-errands", taskrabbitPath: "/services/shopping-delivery/run-errands" },
      { title: "Christmas Tree Delivery", slug: "christmas-tree-delivery", taskrabbitPath: "/services/shopping-delivery/christmas-tree-delivery" },
      { title: "Wait in Line", slug: "waiting-in-line", taskrabbitPath: "/services/shopping-delivery/waiting-in-line" },
      { title: "Deliver Big Piece of Furniture", slug: "deliver-big-piece-of-furniture", taskrabbitPath: "/services/shopping-delivery/deliver-big-piece-of-furniture" },
      { title: "Drop Off Donations", slug: "drop-off-donations", taskrabbitPath: "/services/shopping-delivery/drop-off-donations" },
      { title: "Contactless Delivery", slug: "pick-up-delivery", taskrabbitPath: "/services/shopping-delivery/pick-up-delivery" },
      { title: "Pet Food Delivery", slug: "dog-food-delivery", taskrabbitPath: "/services/shopping-delivery/dog-food-delivery" },
      { title: "Baby Food Delivery", slug: "baby-food-delivery", taskrabbitPath: "/services/shopping-delivery/baby-food-delivery" },
      { title: "Return Items", slug: "return-items", taskrabbitPath: "/services/shopping-delivery/return-items" },
      { title: "Wait for Delivery", slug: "wait-for-delivery", taskrabbitPath: "/services/shopping-delivery/wait-for-delivery" },
      { title: "Shipping", slug: "shipping", taskrabbitPath: "/services/shopping-delivery/shipping" },
      { title: "Breakfast Delivery", slug: "breakfast-delivery", taskrabbitPath: "/services/shopping-delivery/breakfast-delivery" },
      { title: "Coffee Delivery", slug: "coffee-delivery", taskrabbitPath: "/services/shopping-delivery/coffee-delivery" },
    ],
  },
  {
    title: "IKEA Services",
    slug: "ikea-services",
    taskrabbitPath: "/services/ikea-services",
    services: [
      { title: "Light Installation", slug: "light-installation", taskrabbitPath: "/services/ikea-services/light-installation" },
      { title: "Furniture Removal", slug: "furniture-removal", taskrabbitPath: "/services/ikea-services/furniture-removal" },
      { title: "Smart Home Installation", slug: "smart-home-installation", taskrabbitPath: "/services/ikea-services/smart-home-installation" },
      { title: "Organization", slug: "organization", taskrabbitPath: "/services/ikea-services/organization" },
      { title: "Furniture Assembly", slug: "assemble-furniture", taskrabbitPath: "/services/ikea-services/assemble-furniture" },
      { title: "General Mounting", slug: "mounting-all", taskrabbitPath: "/services/ikea-services/mounting-all" },
    ],
  },
  {
    title: "Yardwork Services",
    slug: "yardwork-removal",
    taskrabbitPath: "/services/yardwork-removal",
    services: [
      { title: "Gardening Services", slug: "gardening", taskrabbitPath: "/services/yardwork-removal/gardening" },
      { title: "Weed Removal", slug: "weeding", taskrabbitPath: "/services/yardwork-removal/weeding" },
      { title: "Lawn Care Services", slug: "lawn-care", taskrabbitPath: "/services/yardwork-removal/lawn-care" },
      { title: "Lawn Mowing Services", slug: "lawn-mowing", taskrabbitPath: "/services/yardwork-removal/lawn-mowing" },
      { title: "Landscaping Services", slug: "landscaping", taskrabbitPath: "/services/yardwork-removal/landscaping" },
      { title: "Gutter Cleaning", slug: "gutter-cleaning", taskrabbitPath: "/services/yardwork-removal/gutter-cleaning" },
      { title: "Tree Trimming Service", slug: "tree-trimming", taskrabbitPath: "/services/yardwork-removal/tree-trimming" },
      { title: "Vacation Plant Watering", slug: "vacation-plant-watering", taskrabbitPath: "/services/yardwork-removal/vacation-plant-watering" },
      { title: "Patio Cleaning", slug: "patio-cleaning", taskrabbitPath: "/services/yardwork-removal/patio-cleaning" },
      { title: "Hot Tub Cleaning", slug: "hot-tub-cleaning", taskrabbitPath: "/services/yardwork-removal/hot-tub-cleaning" },
      { title: "Fence Installation & Repair Services", slug: "fence-installation", taskrabbitPath: "/services/yardwork-removal/fence-installation" },
      { title: "Deck Restoration Services", slug: "deck-restoration", taskrabbitPath: "/services/yardwork-removal/deck-restoration" },
      { title: "Patio Furniture Assembly", slug: "patio-furniture-assembly", taskrabbitPath: "/services/yardwork-removal/patio-furniture-assembly" },
      { title: "Fence Staining", slug: "fence-staining", taskrabbitPath: "/services/yardwork-removal/fence-staining" },
      { title: "Mulching Services", slug: "mulching", taskrabbitPath: "/services/yardwork-removal/mulching" },
      { title: "Lawn Fertilizer Service", slug: "lawn-fertilizer", taskrabbitPath: "/services/yardwork-removal/lawn-fertilizer" },
      { title: "Hedge Trimming Service", slug: "hedge-trimming", taskrabbitPath: "/services/yardwork-removal/hedge-trimming" },
      { title: "Outdoor Party Setup", slug: "outdoor-party-setup", taskrabbitPath: "/services/yardwork-removal/outdoor-party-setup" },
      { title: "Urban Gardening Service", slug: "urban-gardening", taskrabbitPath: "/services/yardwork-removal/urban-gardening" },
      { title: "Leaf Raking & Removal", slug: "leaf-removal", taskrabbitPath: "/services/yardwork-removal/leaf-removal" },
      { title: "Produce Gardening", slug: "produce-gardening", taskrabbitPath: "/services/yardwork-removal/produce-gardening" },
      { title: "Hose Installation", slug: "hose-installation", taskrabbitPath: "/services/yardwork-removal/hose-installation" },
      { title: "Shed Maintenance", slug: "shed-maintenance", taskrabbitPath: "/services/yardwork-removal/shed-maintenance" },
      { title: "Pressure Washing", slug: "pressure-washing", taskrabbitPath: "/services/yardwork-removal/pressure-washing" },
    ],
  },
  {
    title: "Holidays",
    slug: "holidays",
    taskrabbitPath: "/services/holidays",
    services: [
      { title: "Gift Wrapping Services", slug: "gift-wrapping", taskrabbitPath: "/services/holidays/gift-wrapping" },
      { title: "Hang Christmas Lights", slug: "christmas-light-installation", taskrabbitPath: "/services/holidays/christmas-light-installation" },
      { title: "Christmas Tree Delivery", slug: "christmas-tree-delivery", taskrabbitPath: "/services/holidays/christmas-tree-delivery" },
      { title: "Holiday Decorating", slug: "christmas-decorator", taskrabbitPath: "/services/holidays/christmas-decorator" },
      { title: "Party Cleaning", slug: "party-cleaning", taskrabbitPath: "/services/holidays/party-cleaning" },
      { title: "Toy Assembly Service", slug: "toy-assembly", taskrabbitPath: "/services/holidays/toy-assembly" },
      { title: "Wait in Line", slug: "waiting-in-line", taskrabbitPath: "/services/holidays/waiting-in-line" },
      { title: "Christmas Tree Removal", slug: "tree-removal", taskrabbitPath: "/services/holidays/tree-removal" },
    ],
  },
  {
    title: "Winter Tasks",
    slug: "winter-tasks",
    taskrabbitPath: "/services/winter-tasks",
    services: [
      { title: "Snow Removal", slug: "snow-removal", taskrabbitPath: "/services/winter-tasks/snow-removal" },
      { title: "Sidewalk Salting", slug: "sidewalk-snow-removal", taskrabbitPath: "/services/winter-tasks/sidewalk-snow-removal" },
      { title: "Window Winterization", slug: "window-winterization", taskrabbitPath: "/services/winter-tasks/window-winterization" },
      { title: "Residential Snow Removal", slug: "residential-snow-removal", taskrabbitPath: "/services/winter-tasks/residential-snow-removal" },
      { title: "Christmas Tree Removal", slug: "tree-removal", taskrabbitPath: "/services/winter-tasks/tree-removal" },
      { title: "AC Winterization", slug: "ac-winterization", taskrabbitPath: "/services/winter-tasks/ac-winterization" },
      { title: "Winter Yardwork", slug: "winter-yardwork", taskrabbitPath: "/services/winter-tasks/winter-yardwork" },
      { title: "Pipe Insulation", slug: "pipe-insulation", taskrabbitPath: "/services/winter-tasks/pipe-insulation" },
      { title: "Storm Door Installation", slug: "storm-door-installation", taskrabbitPath: "/services/winter-tasks/storm-door-installation" },
      { title: "Winter Deck Maintenance", slug: "winter-deck-maintenance", taskrabbitPath: "/services/winter-tasks/winter-deck-maintenance" },
      { title: "Water Heater Maintenance", slug: "water-heater-maintenance", taskrabbitPath: "/services/winter-tasks/water-heater-maintenance" },
      { title: "Wait in Line", slug: "waiting-in-line", taskrabbitPath: "/services/winter-tasks/waiting-in-line" },
    ],
  },
  {
    title: "Personal Assistant",
    slug: "personal-assistant",
    taskrabbitPath: "/services/personal-assistant",
    services: [
      { title: "Personal Assistant", slug: "personal-assistant", taskrabbitPath: "/services/personal-assistant/personal-assistant" },
      { title: "Running Your Errands", slug: "run-errands", taskrabbitPath: "/services/personal-assistant/run-errands" },
      { title: "Wait in Line", slug: "waiting-in-line", taskrabbitPath: "/services/personal-assistant/waiting-in-line" },
      { title: "Organization", slug: "organization", taskrabbitPath: "/services/personal-assistant/organization" },
      { title: "Organize Home", slug: "home-organization", taskrabbitPath: "/services/personal-assistant/home-organization" },
      { title: "Closet Organization Service", slug: "closet-organization", taskrabbitPath: "/services/personal-assistant/closet-organization" },
      { title: "Interior Design Service", slug: "interior-design", taskrabbitPath: "/services/personal-assistant/interior-design" },
      { title: "Virtual Assistant", slug: "virtual-assistant", taskrabbitPath: "/services/personal-assistant/virtual-assistant" },
    ],
  },
  {
    title: "Baby Prep",
    slug: "baby-prep",
    taskrabbitPath: "/services/baby-prep",
    services: [
      { title: "Baby Proofing", slug: "baby-proofing", taskrabbitPath: "/services/baby-prep/baby-proofing" },
      { title: "Baby Food Delivery", slug: "baby-food-delivery", taskrabbitPath: "/services/baby-prep/baby-food-delivery" },
      { title: "Organize a Room", slug: "organize-a-room", taskrabbitPath: "/services/baby-prep/organize-a-room" },
      { title: "Painting", slug: "painting", taskrabbitPath: "/services/baby-prep/painting" },
      { title: "Toy Assembly Service", slug: "toy-assembly", taskrabbitPath: "/services/baby-prep/toy-assembly" },
      { title: "Smart Home Installation", slug: "smart-home-installation", taskrabbitPath: "/services/baby-prep/smart-home-installation" },
      { title: "Shopping", slug: "need-us-to-shop-for-something", taskrabbitPath: "/services/baby-prep/need-us-to-shop-for-something" },
      { title: "General Cleaning", slug: "need-something-else-cleaned", taskrabbitPath: "/services/baby-prep/need-something-else-cleaned" },
    ],
  },
  {
    title: "Virtual & Online Tasks",
    slug: "online-tasks",
    taskrabbitPath: "/services/online-tasks",
    services: [
      { title: "Virtual Assistant", slug: "virtual-assistant", taskrabbitPath: "/services/online-tasks/virtual-assistant" },
      { title: "Organization", slug: "organization", taskrabbitPath: "/services/online-tasks/organization" },
      { title: "Data Entry", slug: "data-entry-clerk", taskrabbitPath: "/services/online-tasks/data-entry-clerk" },
      { title: "Computer Help", slug: "computer-help", taskrabbitPath: "/services/online-tasks/computer-help" },
    ],
  },
  {
    title: "Office Services",
    slug: "office",
    taskrabbitPath: "/services/office",
    services: [
      { title: "Office Cleaning", slug: "commercial-cleaning", taskrabbitPath: "/services/office/commercial-cleaning" },
      { title: "Office Tech Setup", slug: "conference-room", taskrabbitPath: "/services/office/conference-room" },
      { title: "Office Movers", slug: "movers", taskrabbitPath: "/services/office/movers" },
      { title: "Office Supply & Snack Delivery", slug: "supply-snack-delivery", taskrabbitPath: "/services/office/supply-snack-delivery" },
      { title: "Office Furniture Assembly", slug: "furniture-assembly-setup", taskrabbitPath: "/services/office/furniture-assembly-setup" },
      { title: "Office Setup & Organization", slug: "organization-setup", taskrabbitPath: "/services/office/organization-setup" },
      { title: "Office Administration", slug: "office-administration", taskrabbitPath: "/services/office/office-administration" },
      { title: "Office Interior Design", slug: "office-interior-design", taskrabbitPath: "/services/office/office-interior-design" },
      { title: "Moving Office Furniture", slug: "office-furniture-moving", taskrabbitPath: "/services/office/office-furniture-moving" },
      { title: "Office Mounting Service", slug: "office-mounting", taskrabbitPath: "/services/office/office-mounting" },
    ],
  },
  {
    title: "Contactless Tasks",
    slug: "contactless",
    taskrabbitPath: "/services/contactless",
    services: [
      { title: "Contactless Delivery", slug: "pick-up-delivery", taskrabbitPath: "/services/contactless/pick-up-delivery" },
      { title: "Contactless Prescription Pick-up & Delivery", slug: "prescription-delivery", taskrabbitPath: "/services/contactless/prescription-delivery" },
      { title: "Running Your Errands", slug: "run-errands", taskrabbitPath: "/services/contactless/run-errands" },
      { title: "Grocery Shopping & Delivery", slug: "grocery-shopping", taskrabbitPath: "/services/contactless/grocery-shopping" },
      { title: "Disinfecting Services", slug: "disinfecting-service", taskrabbitPath: "/services/contactless/disinfecting-service" },
      { title: "Drop Off Donations", slug: "drop-off-donations", taskrabbitPath: "/services/contactless/drop-off-donations" },
      { title: "Yard Work Services", slug: "yard-work-removal", taskrabbitPath: "/services/contactless/yard-work-removal" },
      { title: "Virtual Assistant", slug: "virtual-assistant", taskrabbitPath: "/services/contactless/virtual-assistant" },
    ],
  },
];

function customJobHref(query: string) {
  return `/questionnaire?category=custom&subcategory=custom-job&custom_query=${encodeURIComponent(query)}&source=taskrabbit`;
}

export function getTaskrabbitCategoryHref(category: TaskrabbitCategory) {
  return customJobHref(category.title);
}

export function getTaskrabbitServiceHref(service: TaskrabbitService) {
  return customJobHref(service.title);
}
