import { useQuery } from "@tanstack/react-query";
import { Award, Briefcase, CircleDollarSign, Star } from "lucide-react-native";
import { StyleSheet, Text, View } from "react-native";
import { api } from "@/lib/api";
import { Card, ErrorState, Header, LoadingState, Screen } from "@/components/ui";
import { colors } from "@/theme/tokens";

export default function AnalyticsScreen() { const query = useQuery({ queryKey: ["provider-analytics"], queryFn: () => api<any>("/api/provider/dashboard-data") }); if (query.isLoading) return <Screen><LoadingState /></Screen>; if (query.isError) return <Screen><ErrorState message={(query.error as Error).message} /></Screen>; const data = query.data; const reviews = data.reviews || []; const requestJobs = data.completedServiceJobs || []; const completed = (data.bookings?.length || 0) + requestJobs.length + (data.shiftApplications?.length || 0); const revenue = requestJobs.reduce((sum: number, item: any) => sum + Number(item.amount || 0), 0) + (data.shiftApplications || []).reduce((sum: number, item: any) => sum + Number(item.payment?.agreed_amount || 0), 0) + (data.bookings || []).reduce((sum: number, item: any) => sum + Number(item.total_price || 0), 0); const rating = reviews.length ? reviews.reduce((sum: number, item: any) => sum + Number(item.rating), 0) / reviews.length : 0; const stats = [["Completed work", completed, Briefcase, colors.info], ["Recorded earnings", `€${revenue.toFixed(2)}`, CircleDollarSign, colors.success], ["Average rating", rating ? rating.toFixed(1) : "New", Star, "#f4b400"], ["Badges earned", data.badges?.length || 0, Award, colors.brand]] as const; return <Screen><Header title="Analytics" subtitle="Live completion, review, badge, and earnings data." /><View style={styles.grid}>{stats.map(([label, value, Icon, color]) => <Card key={label} style={styles.stat}><Icon color={color} /><Text style={styles.value}>{value}</Text><Text style={styles.label}>{label}</Text></Card>)}</View><Card><Text style={styles.heading}>Work composition</Text><View style={styles.line}><Text style={styles.label}>Service jobs</Text><Text style={styles.bold}>{(data.bookings?.length || 0) + requestJobs.length}</Text></View><View style={styles.line}><Text style={styles.label}>Business shifts</Text><Text style={styles.bold}>{data.shiftApplications?.length || 0}</Text></View><View style={styles.line}><Text style={styles.label}>Public reviews</Text><Text style={styles.bold}>{reviews.length}</Text></View></Card></Screen>; }
const styles = StyleSheet.create({ grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, stat: { flexBasis: "45%", flexGrow: 1 }, value: { color: colors.ink, fontWeight: "900", fontSize: 25 }, label: { color: colors.muted }, heading: { color: colors.ink, fontWeight: "900", fontSize: 19 }, line: { flexDirection: "row", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: colors.line, paddingVertical: 10 }, bold: { color: colors.ink, fontWeight: "800" } });
