import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { Alert, StyleSheet, Text, View } from "react-native";
import { api, jsonBody } from "@/lib/api";
import { Avatar, Button, Card, EmptyState, ErrorState, Header, LoadingState, Pill, Screen } from "@/components/ui";
import { colors } from "@/theme/tokens";

export default function BusinessApplicationsScreen() {
  const query = useQuery({ queryKey: ["business-applications"], queryFn: () => api<any>("/api/business/shift-applications") }); const client = useQueryClient(); const router = useRouter(); const action = useMutation({ mutationFn: ({ id, action }: { id: string; action: string }) => api("/api/business/shift-applications", { method: "POST", ...jsonBody({ applicationId: id, action }) }), onSuccess: () => { void query.refetch(); void client.invalidateQueries({ queryKey: ["business-posts"] }); void client.invalidateQueries({ queryKey: ["notifications"] }); void client.invalidateQueries({ queryKey: ["earnings"] }); }, onError: (error: Error) => Alert.alert("Action failed", error.message) }); const rows = query.data?.applications || [];
  return <Screen><Header title="Shift applications" subtitle="Accept, fund, complete, review, and notify workers." />{query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message={(query.error as Error).message} /> : rows.length === 0 ? <EmptyState title="No applications yet" body="Applications from eligible shift workers appear here." /> : rows.map((item: any) => { const name = [item.provider?.first_name, item.provider?.last_name].filter(Boolean).join(" ") || "Shift worker"; const payment = item.payment; const reviewed = (item.reviews || []).some((review: any) => review.review_type === "buyer_to_seller"); return <Card key={item.id}><View style={styles.row}><Avatar name={name} /><View style={{ flex: 1 }}><Text style={styles.name}>{name}</Text><Text style={styles.muted}>{item.post?.role_title || "Shift"} · {item.post?.city}</Text></View><Pill text={item.status} tone={item.status === "completed" ? "success" : "info"} /></View>{item.message ? <Text style={styles.message}>{item.message}</Text> : null}{item.status === "applied" ? <View style={styles.actions}><Button title="Accept" loading={action.isPending} onPress={() => action.mutate({ id: item.id, action: "accept" })} /><Button title="Reject" variant="secondary" onPress={() => action.mutate({ id: item.id, action: "reject" })} /></View> : null}{item.status === "accepted" && payment?.status === "requires_payment" ? <Button title="Pay shift (test payment)" onPress={() => action.mutate({ id: item.id, action: "pay" })} /> : null}{item.status === "accepted" && payment?.status === "held" ? <Button title="Mark shift complete" onPress={() => action.mutate({ id: item.id, action: "complete" })} /> : null}{item.status === "completed" ? reviewed ? <Pill text="Review submitted" tone="success" /> : <Button title="Review worker" onPress={() => router.push(`/review/new?shiftApplicationId=${item.id}&type=buyer_to_seller&revieweeId=${item.provider_user_id}`)} /> : null}</Card>; })}</Screen>;
}
const styles = StyleSheet.create({ row: { flexDirection: "row", alignItems: "center", gap: 10 }, name: { color: colors.ink, fontWeight: "800", fontSize: 17 }, muted: { color: colors.muted }, message: { color: colors.muted, lineHeight: 20 }, actions: { gap: 8 } });
