import { useQuery } from "@tanstack/react-query";
import { Search, Star, UserRound } from "lucide-react-native";
import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { api } from "@/lib/api";
import { Button, Card, EmptyState, ErrorState, Field, Header, LoadingState, Pill, Screen } from "@/components/ui";
import { colors } from "@/theme/tokens";

export default function BusinessWorkersScreen() {
  const [draft, setDraft] = useState(""); const [niche, setNiche] = useState(""); const query = useQuery({ queryKey: ["business-workers", niche], queryFn: () => api<any>(`/api/business/shift-workers?niche=${encodeURIComponent(niche)}`), enabled: Boolean(niche) }); const workers = query.data?.workers || [];
  return <Screen><Header title="Shift workers" subtitle="Search approved, available workers by marketplace niche." /><Card><Field label="Worker niche" placeholder="e.g. hospitality" value={draft} autoCapitalize="none" onChangeText={setDraft} /><Button title="Search workers" icon={<Search color="white" size={18} />} disabled={!draft.trim()} onPress={() => setNiche(draft.trim())} /></Card>{!niche ? <EmptyState title="Choose a niche" body="Matching available workers will appear here." /> : query.isLoading ? <LoadingState label="Finding matching workers…" /> : query.isError ? <ErrorState message={(query.error as Error).message} retry={() => void query.refetch()} /> : workers.length === 0 ? <EmptyState title="No available workers" body={`No approved workers currently match ${niche}.`} /> : workers.map((worker: any) => { const profile = worker.profile || {}; const seller = worker.seller || {}; const name = [profile.first_name || seller.first_name, profile.last_name || seller.last_name].filter(Boolean).join(" ") || "Shift worker"; return <Card key={worker.id || worker.user_id}><View style={styles.head}><View style={styles.avatar}><UserRound color={colors.brand} /></View><View style={{ flex: 1 }}><Text style={styles.name}>{name}</Text><Text style={styles.meta}>{profile.city || seller.city || "Location available after matching"}</Text></View><Pill text="Available" tone="success" /></View><Text style={styles.meta}>{(worker.preferred_roles || []).join(", ") || seller.service_category || niche}</Text>{Number(seller.rating) > 0 && Number(seller.total_jobs) > 0 ? <View style={styles.rating}><Star color="#f4b400" fill="#f4b400" size={17} /><Text style={styles.ratingText}>{Number(seller.rating).toFixed(1)} · {seller.total_jobs} jobs</Text></View> : null}</Card>; })}</Screen>;
}
const styles = StyleSheet.create({ head: { flexDirection: "row", alignItems: "center", gap: 11 }, avatar: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: colors.soft }, name: { color: colors.ink, fontWeight: "900", fontSize: 18 }, meta: { color: colors.muted, lineHeight: 20 }, rating: { flexDirection: "row", alignItems: "center", gap: 6 }, ratingText: { color: colors.ink, fontWeight: "700" } });
