import { useQuery } from "@tanstack/react-query";
import { CircleDollarSign } from "lucide-react-native";
import { StyleSheet, Text, View } from "react-native";
import { api } from "@/lib/api";
import { Card, EmptyState, ErrorState, Header, LoadingState, Pill, Screen } from "@/components/ui";
import { colors } from "@/theme/tokens";

export default function EarningsScreen() {
  const query = useQuery({ queryKey: ["wallet"], queryFn: () => api<any>("/api/provider/wallet") }); if (query.isLoading) return <Screen><LoadingState /></Screen>; if (query.isError) return <Screen><ErrorState message={(query.error as Error).message} /></Screen>; const data = query.data; const rows = data.entries || [];
  return <Screen><Header title="Earnings" subtitle="Shift escrow credits and provider wallet history." /><View style={styles.totals}><Card style={styles.total}><Text style={styles.label}>Available</Text><Text style={styles.available}>€{Number(data.totals?.available || 0).toFixed(2)}</Text></Card><Card style={styles.total}><Text style={styles.label}>Pending</Text><Text style={styles.value}>€{Number(data.totals?.pending || 0).toFixed(2)}</Text></Card><Card style={styles.total}><Text style={styles.label}>Paid out</Text><Text style={styles.value}>€{Number(data.totals?.paidOut || 0).toFixed(2)}</Text></Card></View>{rows.length === 0 ? <EmptyState title="No earnings yet" body="Released business shift payments appear here." /> : rows.map((entry: any) => <Card key={entry.id}><View style={styles.row}><CircleDollarSign color={colors.success} /><View style={{ flex: 1 }}><Text style={styles.description}>{entry.description || "AnyJob payment"}</Text><Text style={styles.date}>{entry.created_at ? new Date(entry.created_at).toLocaleDateString() : ""}</Text></View><View style={styles.right}><Text style={styles.amount}>€{Number(entry.amount).toFixed(2)}</Text><Pill text={entry.status} tone={entry.status === "available" ? "success" : "warning"} /></View></View></Card>)}</Screen>;
}
const styles = StyleSheet.create({ totals: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, total: { flexGrow: 1, flexBasis: 110 }, label: { color: colors.muted, fontWeight: "700" }, value: { color: colors.ink, fontWeight: "900", fontSize: 22 }, available: { color: colors.success, fontWeight: "900", fontSize: 22 }, row: { flexDirection: "row", gap: 10, alignItems: "center" }, description: { color: colors.ink, fontWeight: "800" }, date: { color: colors.muted, fontSize: 12 }, right: { alignItems: "flex-end", gap: 4 }, amount: { color: colors.success, fontWeight: "900", fontSize: 18 } });
