import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Trash2 } from "lucide-react-native";
import { useState } from "react";
import { Alert, StyleSheet, Text, View } from "react-native";
import { api, jsonBody } from "@/lib/api";
import { Button, Card, EmptyState, ErrorState, Field, Header, LoadingState, Pill, Screen } from "@/components/ui";
import { colors } from "@/theme/tokens";

export default function ServicesScreen() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["provider-services"], queryFn: () => api<any>("/api/provider/services") }); const [editing, setEditing] = useState<any | null>(null); const [deletingId, setDeletingId] = useState<string | null>(null); const [form, setForm] = useState({ title: "", description: "", hourlyRate: "25", minHours: "1", maxRadiusKm: "25", tags: "" }); const open = (item?: any) => { setEditing(item || {}); setForm({ title: item?.title || "", description: item?.description || "", hourlyRate: String(item?.hourly_rate || 25), minHours: String(item?.min_hours || 1), maxRadiusKm: String(item?.max_radius_km || 25), tags: (item?.tags || []).join(", ") }); }; const set = (key: keyof typeof form) => (value: string) => setForm((current) => ({ ...current, [key]: value })); const save = useMutation({ mutationFn: () => api("/api/provider/services", { method: editing?.id ? "PATCH" : "POST", ...jsonBody({ id: editing?.id, title: form.title, description: form.description, hourlyRate: Number(form.hourlyRate), minHours: Number(form.minHours), maxRadiusKm: Number(form.maxRadiusKm), tags: form.tags.split(",").map((x) => x.trim()).filter(Boolean), isActive: true, gigDetails: { category: "General", packages: [{ title: "Starter", description: form.description, price: Number(form.hourlyRate), deliveryDays: 1, revisions: 1 }], faqs: [], requirementQuestions: ["What work do you need?", "When should it be completed?"] } }) }), onSuccess: () => { setEditing(null); void client.invalidateQueries({ queryKey: ["provider-services"] }); }, onError: (error: Error) => Alert.alert("Could not save service", error.message) }); const remove = useMutation({ mutationFn: (id: string) => api(`/api/provider/services?id=${id}`, { method: "DELETE" }), onSuccess: () => { setDeletingId(null); void client.invalidateQueries({ queryKey: ["provider-services"] }); }, onError: (error: Error) => Alert.alert("Could not delete service", error.message) }); const rows = query.data?.services || [];
  return <Screen><Header title="My services" subtitle="Publish packages buyers can inspect on your marketplace profile." action={<Button title="New" icon={<Plus color="white" size={17} />} onPress={() => open()} />} />{editing ? <Card><Field label="Gig title" value={form.title} onChangeText={set("title")} /><Field label="Description" multiline value={form.description} onChangeText={set("description")} /><Field label="Starting price (€)" keyboardType="decimal-pad" value={form.hourlyRate} onChangeText={set("hourlyRate")} /><Field label="Minimum hours" keyboardType="number-pad" value={form.minHours} onChangeText={set("minHours")} /><Field label="Travel radius (km)" keyboardType="number-pad" value={form.maxRadiusKm} onChangeText={set("maxRadiusKm")} /><Field label="Search tags (comma-separated)" value={form.tags} onChangeText={set("tags")} /><Button title={editing.id ? "Save changes" : "Publish service"} loading={save.isPending} disabled={!form.title || !form.description} onPress={() => save.mutate()} /><Button title="Cancel" variant="ghost" onPress={() => setEditing(null)} /></Card> : null}{query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message={(query.error as Error).message} /> : rows.length === 0 ? <EmptyState title="No service gigs" body="Publish a service so buyers can discover and book your work." /> : rows.map((item: any) => <Card key={item.id}><View style={styles.head}><View style={{ flex: 1 }}><Text style={styles.title}>{item.title}</Text><Text style={styles.body}>{item.description}</Text></View><Pill text={item.is_active ? "Active" : "Paused"} tone={item.is_active ? "success" : "warning"} /></View><Text style={styles.price}>From €{Number(item.hourly_rate).toFixed(2)}</Text><Button title="Edit service" variant="secondary" onPress={() => open(item)} />{deletingId === item.id ? <><Text style={styles.body}>Delete this service permanently?</Text><Button title="Confirm delete" variant="danger" loading={remove.isPending} onPress={() => remove.mutate(item.id)} /><Button title="Cancel delete" variant="ghost" onPress={() => setDeletingId(null)} /></> : <Button title="Delete" variant="ghost" icon={<Trash2 color={colors.danger} size={18} />} onPress={() => setDeletingId(item.id)} />}</Card>)}</Screen>;
}
const styles = StyleSheet.create({ head: { flexDirection: "row", gap: 10 }, title: { color: colors.ink, fontWeight: "900", fontSize: 19 }, body: { color: colors.muted, lineHeight: 21 }, price: { color: colors.success, fontWeight: "900", fontSize: 19 } });
