create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity unique,
  user_id uuid references auth.users(id) on delete set null,
  requester_email text not null,
  requester_name text,
  requester_type text not null default 'user',
  title text not null,
  description text not null,
  category text not null default 'general',
  priority text not null default 'normal',
  status text not null default 'open',
  source_path text,
  related_job_id text,
  assigned_admin_id uuid references auth.users(id) on delete set null,
  last_user_response_at timestamptz,
  last_admin_response_at timestamptz,
  resolved_at timestamptz,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint support_tickets_requester_type_check check (requester_type in ('user', 'business', 'provider', 'contractor')),
  constraint support_tickets_priority_check check (priority in ('low', 'normal', 'high', 'urgent')),
  constraint support_tickets_status_check check (status in ('open', 'in_progress', 'waiting_user', 'resolved', 'closed'))
);

create table if not exists public.support_ticket_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  sender_user_id uuid references auth.users(id) on delete set null,
  sender_role text not null default 'user',
  body text not null,
  internal_note boolean not null default false,
  created_at timestamptz not null default now(),
  constraint support_ticket_messages_sender_role_check check (sender_role in ('user', 'admin', 'system')),
  constraint support_ticket_messages_body_not_empty check (length(trim(body)) > 0)
);

create index if not exists idx_support_tickets_status on public.support_tickets(status);
create index if not exists idx_support_tickets_requester_type on public.support_tickets(requester_type);
create index if not exists idx_support_tickets_category on public.support_tickets(category);
create index if not exists idx_support_tickets_priority on public.support_tickets(priority);
create index if not exists idx_support_tickets_user_id on public.support_tickets(user_id);
create index if not exists idx_support_tickets_created_at on public.support_tickets(created_at desc);
create index if not exists idx_support_ticket_messages_ticket_id on public.support_ticket_messages(ticket_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_support_tickets_updated_at on public.support_tickets;
create trigger set_support_tickets_updated_at
  before update on public.support_tickets
  for each row execute function public.set_updated_at();

alter table public.support_tickets enable row level security;
alter table public.support_ticket_messages enable row level security;

drop policy if exists "Users can read own support tickets" on public.support_tickets;
create policy "Users can read own support tickets"
  on public.support_tickets for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can create own support tickets" on public.support_tickets;
create policy "Users can create own support tickets"
  on public.support_tickets for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can read own support ticket messages" on public.support_ticket_messages;
create policy "Users can read own support ticket messages"
  on public.support_ticket_messages for select
  to authenticated
  using (
    exists (
      select 1
      from public.support_tickets ticket
      where ticket.id = support_ticket_messages.ticket_id
        and ticket.user_id = (select auth.uid())
    )
  );

drop policy if exists "Users can add messages to own support tickets" on public.support_ticket_messages;
create policy "Users can add messages to own support tickets"
  on public.support_ticket_messages for insert
  to authenticated
  with check (
    sender_user_id = (select auth.uid())
    and sender_role = 'user'
    and internal_note = false
    and exists (
      select 1
      from public.support_tickets ticket
      where ticket.id = support_ticket_messages.ticket_id
        and ticket.user_id = (select auth.uid())
        and ticket.status in ('open', 'in_progress', 'waiting_user')
    )
  );
